node {
  
  stage('Preparation') {
    checkout scm
  }
  stage('test') {
    nodejs(nodeJSInstallationName: 'nodejs') {
     sh 'npm install --only=dev'
     sh 'npm test'
    }
  }
  stage('test in container') {
    docker.image('node:4.6').inside {
     sh 'npm install --only=dev'
     sh 'npm test'
    }
  }
  stage('docker build/push') {
    sh "git rev-parse --short HEAD > .git/commit-id"                        
    def commit_id = readFile('.git/commit-id').trim()
    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
     docker.build("yaozhiqun/docker-nodejs-demo:${commit_id}", '.').push()
    }
  }
  stage('do something with git') {  
    sshagent (credentials: ['github']) {
      // get the last commit id from a repository you own
      sh 'git ls-remote -h --refs git@github.com:yaozhiqun/docker-demo.git master |awk "{print $1}"'
    }
  }
}
