node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("yaozhiqun/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }

  stage('do something with git') {  
    sshagent (credentials: ['github']) {
      // get the last commit id from a repository you own
      sh 'git ls-remote -h --refs git@github.com:yaozhiqun/docker-demo.git master |awk "{print $1}"'
    }
  }
}
